### ISSUE TITLE
TestFetchCommand is flaky, fails occassionally on CI, and shouldn't run `connect`

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1046]
Sometimes this test fails with:
```
=== RUN   TestFetchCommand
17:38:33.564 ERROR     qrip2p: error adding peer: open /tmp/qri_test_commands_connect/qri/peers.json.lock: no such file or directory bootstrap.go:30
17:38:33.566 ERROR     qrip2p: error adding peer: open /tmp/qri_test_commands_connect/qri/peers.json.lock: no such file or directory bootstrap.go:30
17:38:33.570 ERROR     qrip2p: error adding peer: open /tmp/qri_test_commands_connect/qri/peers.json.lock: no such file or directory bootstrap.go:30
17:38:33.578 ERROR     qrip2p: error adding peer: open /tmp/qri_test_commands_connect/qri/peers.json.lock: no such file or directory bootstrap.go:30
17:38:38.619 ERROR     flatfs: could not store final value of disk usage to file, future estimates may be inaccurate flatfs.go:883
--- FAIL: TestFetchCommand (5.14s)
    fetch_test.go:68: Get http://localhost:2503/remote/logsync?ref=peer_a/test_movies: dial tcp 127.0.0.1:2503: connect: connection refused
```

Also, since it runs `qri connect`, there's race conditions with other tests, they may change behavior if they think connect is running.

**Comment by dustmop** [comment]
Got a new error in this test:
```
--- FAIL: TestFetchCommand (6.82s)
    fetch_test.go:68: Get http://localhost:2503/remote/logsync?ref=peer_a/test_movies: dial tcp [::1]:2503: connect: connection refused
18:35:23.980 ERROR     flatfs: could not store final value of disk usage to file, future estimates may be inaccurate flatfs.go:883
18:35:24.292 ERROR     flatfs: could not store final value of disk usage to file, future estimates may be inaccurate flatfs.go:883
panic: Fail in goroutine after TestFetchCommand has completed

goroutine 2775 [running]:
testing.(*common).Fail(0xc0000eb100)
	/usr/local/go/src/testing/testing.go:609 +0x151
testing.(*common).FailNow(0xc0000eb100)
	/usr/local/go/src/testing/testing.go:631 +0x2b
testing.(*common).Fatal(0xc0000eb100, 0xc0008f9fa8, 0x1, 0x1)
	/usr/local/go/src/testing/testing.go:710 +0x78
github.com/qri-io/qri/cmd.TestFetchCommand.func1(0xc00085ca00, 0xc0003fdff0, 0xc0000eb100)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/cmd/fetch_test.go:46 +0xac
created by github.com/qri-io/qri/cmd.TestFetchCommand
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/cmd/fetch_test.go:44 +0x53c
FAIL	github.com/qri-io/qri/cmd	59.187s
FAIL
```

**Comment by dustmop** [comment]
Just got this one:

```
10:47:55.687 ERROR     qrip2p: error adding peer: open /var/folders/dr/99mxhb715495lk6rc4zy5dfr0000gn/T/qri_test_commands_connect/qri/peers.json.lock: no such file or directory bootstrap.go:30
10:47:55.719 ERROR     qrip2p: error adding peer: open /var/folders/dr/99mxhb715495lk6rc4zy5dfr0000gn/T/qri_test_commands_connect/qri/peers.json.lock: no such file or directory bootstrap.go:30
10:47:56.002 ERROR     qrip2p: error adding peer: open /var/folders/dr/99mxhb715495lk6rc4zy5dfr0000gn/T/qri_test_commands_connect/qri/peers.json.lock: no such file or directory bootstrap.go:30
10:47:56.002 ERROR     qrip2p: error adding peer: open /var/folders/dr/99mxhb715495lk6rc4zy5dfr0000gn/T/qri_test_commands_connect/qri/peers.json.lock: no such file or directory bootstrap.go:30
10:47:58.344 ERROR     flatfs: could not store final value of disk usage to file, future estimates may be inaccurate flatfs.go:883
--- FAIL: TestFetchCommand (5.60s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x505f4de]

goroutine 2485 [running]:
testing.tRunner.func1(0xc001845600)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x53b8000, 0x670f3d0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/qri-io/qri/lib.(*RemoteMethods).Fetch(0xc00183eda0, 0xc03fc7a9a0, 0xc03fc7a980, 0xc03b98da00, 0x45f337e)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/lib/remote.go:69 +0x2ce
github.com/qri-io/qri/cmd.(*FetchOptions).Run(0xc03fb30a10, 0xc00183eda0, 0x0)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/cmd/fetch.go:63 +0x25a
github.com/qri-io/qri/cmd.NewFetchCommand.func1(0xc03fb52c80, 0xc03fb60a80, 0x1, 0x3, 0x0, 0x0)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/cmd/fetch.go:26 +0xaa
github.com/spf13/cobra.(*Command).execute(0xc03fb52c80, 0xc03fb609f0, 0x3, 0x3, 0xc03fb52c80, 0xc03fb609f0)
	/Users/dlong/dev/code/go/qri/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc03faa2780, 0x6, 0x560cfb0, 0x1)
	/Users/dlong/dev/code/go/qri/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/qri-io/qri/cmd.executeCommandC(...)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/cmd/test_runner_test.go:226
github.com/qri-io/qri/cmd.executeCommand(0xc03faa2780, 0x565fc8d, 0x2c, 0xc03faa2780, 0x0)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/cmd/test_runner_test.go:221 +0xd0
github.com/qri-io/qri/cmd.TestFetchCommand(0xc001845600)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/cmd/fetch_test.go:67 +0x725
testing.tRunner(0xc001845600, 0x57d3e08)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	github.com/qri-io/qri/cmd	30.369s
```

**Comment by dustmop** [comment]
Failure just now on CI:

```
=== RUN   TestFetchCommand
16:04:08.484 ERROR     flatfs: could not store final value of disk usage to file, future estimates may be inaccurate flatfs.go:883
--- FAIL: TestFetchCommand (5.09s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x1c381fe]

goroutine 3202 [running]:
testing.tRunner.func1(0xc03becdb00)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x1fa5400, 0x31b4ff0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/qri-io/qri/lib.(*RemoteMethods).Fetch(0xc03fd98588, 0xc03feaa180, 0xc03feaa160, 0xc0006c9a00, 0x11cba0e)
	/go/src/github.com/qri-io/qri/lib/remote.go:69 +0x2ce
github.com/qri-io/qri/cmd.(*FetchOptions).Run(0xc03fd22d20, 0xc03fd98588, 0x0)
	/go/src/github.com/qri-io/qri/cmd/fetch.go:63 +0x29a
github.com/qri-io/qri/cmd.NewFetchCommand.func1(0xc03fd42500, 0xc03fd4e900, 0x1, 0x3, 0x0, 0x0)
	/go/src/github.com/qri-io/qri/cmd/fetch.go:26 +0xec
github.com/spf13/cobra.(*Command).execute(0xc03fd42500, 0xc03fd4e870, 0x3, 0x3, 0xc03fd42500, 0xc03fd4e870)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc03fd3a000, 0x6, 0x21fd190, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/qri-io/qri/cmd.executeCommandC(...)
	/go/src/github.com/qri-io/qri/cmd/test_runner_test.go:226
github.com/qri-io/qri/cmd.executeCommand(0xc03fd3a000, 0x2250b15, 0x2c, 0xc03fd3a000, 0x0)
	/go/src/github.com/qri-io/qri/cmd/test_runner_test.go:221 +0xd0
github.com/qri-io/qri/cmd.TestFetchCommand(0xc03becdb00)
	/go/src/github.com/qri-io/qri/cmd/fetch_test.go:67 +0x725
testing.tRunner(0xc03becdb00, 0x23c42a0)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
FAIL	github.com/qri-io/qri/cmd	20.651s
?   	github.com/qri-io/qri/cmd/generate	[no test files]
```
