### ISSUE TITLE
TestRemoveEvenIfLogbookGone is flaky, sometimes flatbuffers panics

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1136]
Seen on CI:

```
=== RUN   TestRemoveEvenIfLogbookGone
19:17:38.652 ERROR     flatfs: could not store final value of disk usage to file, future estimates may be inaccurate flatfs.go:883
19:17:41.516 ERROR    dscache: dscache: does not exist dscache.go:197
panic: runtime error: index out of range [3] with length 0

goroutine 10518 [running]:
github.com/google/flatbuffers/go.GetInt32(...)
	/go/pkg/mod/github.com/google/flatbuffers@v1.11.0/go/encode.go:85
github.com/google/flatbuffers/go.GetUOffsetT(...)
	/go/pkg/mod/github.com/google/flatbuffers@v1.11.0/go/encode.go:121
github.com/qri-io/qri/repo/repo_fbs.GetRootAsReflist(...)
	/go/src/github.com/qri-io/qri/repo/repo_fbs/Reflist.go:14
github.com/qri-io/qri/repo.UnmarshalRefsFlatbuffer(0xc071964400, 0x0, 0x200, 0x0, 0x200, 0x0, 0x0, 0xc063b0fd10)
	/go/src/github.com/qri-io/qri/repo/serialize.go:48 +0x2e6
github.com/qri-io/qri/repo/fs.(*Refstore).refs(0xc0027dd2d0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/qri-io/qri/repo/fs/refstore.go:133 +0x2fd
github.com/qri-io/qri/repo/fs.Refstore.GetRef(0xc0717a9b90, 0x2c, 0x8, 0x263f780, 0xc07191c440, 0xc0717c3130, 0x9, 0xc071916d50, 0x22, 0x226fa83, ...)
	/go/src/github.com/qri-io/qri/repo/fs/refstore.go:62 +0x65
github.com/qri-io/qri/repo.CanonicalizeDatasetRef(0x2654ba0, 0xc071936000, 0xc06e2c1620, 0x22, 0x1)
	/go/src/github.com/qri-io/qri/repo/store.go:47 +0x1f7
github.com/qri-io/qri/base.DatasetLogFromHistory(0x2632c60, 0xc0000420e0, 0x2654ba0, 0xc071936000, 0xc0717c3130, 0x9, 0x0, 0x0, 0x226fa83, 0x11, ...)
	/go/src/github.com/qri-io/qri/base/log.go:70 +0x135
github.com/qri-io/qri/base.constructDatasetLogFromHistory(0x2632c60, 0xc0000420e0, 0x2654ba0, 0xc071936000, 0xc0717c3130, 0x9, 0xc0719ae3c0, 0x2e, 0x226fa83, 0x11, ...)
	/go/src/github.com/qri-io/qri/base/log.go:131 +0x12c
github.com/qri-io/qri/base.DatasetLog.func1(0x2654ba0, 0xc071936000, 0xc0717c3130, 0x9, 0xc071916d50, 0x22, 0x226fa83, 0x11, 0xc07193a100, 0x34, ...)
	/go/src/github.com/qri-io/qri/base/log.go:56 +0x106
created by github.com/qri-io/qri/base.DatasetLog
	/go/src/github.com/qri-io/qri/base/log.go:55 +0x334
FAIL	github.com/qri-io/qri/cmd	138.762s
```

**Comment by dustmop** [comment]
Saw this again today:

```
=== RUN   TestRemoveEvenIfLogbookGone
 
panic: runtime error: index out of range [3] with length 0
 

 
goroutine 10037 [running]:
 
github.com/google/flatbuffers/go.GetInt32(...)
 
	/go/pkg/mod/github.com/google/flatbuffers@v1.11.0/go/encode.go:85
 
github.com/google/flatbuffers/go.GetUOffsetT(...)
 
	/go/pkg/mod/github.com/google/flatbuffers@v1.11.0/go/encode.go:121
 
github.com/qri-io/qri/repo/repo_fbs.GetRootAsReflist(...)
 
	/go/src/github.com/qri-io/qri/repo/repo_fbs/Reflist.go:14
 
github.com/qri-io/qri/repo.UnmarshalRefsFlatbuffer(0xc000db4000, 0x0, 0x304, 0x0, 0x304, 0x0, 0x0, 0x16)
 
	/go/src/github.com/qri-io/qri/repo/serialize.go:48 +0x2e6
 
github.com/qri-io/qri/repo/fs.(*Refstore).refs(0xc03dc05278, 0xa, 0x1f3b5a0, 0xc000381af0, 0x1f3b5a0, 0xc000381af0)
 
	/go/src/github.com/qri-io/qri/repo/fs/refstore.go:133 +0x2fd
 
github.com/qri-io/qri/repo/fs.Refstore.GetRef(0xc03fb12ab0, 0x2c, 0x8, 0x270c160, 0xc000b5a260, 0xc000582800, 0x9, 0xc000aa4090, 0x22, 0x2301664, ...)
 
	/go/src/github.com/qri-io/qri/repo/fs/refstore.go:62 +0x65
 
github.com/qri-io/qri/repo.CanonicalizeDatasetRef(0x271faa0, 0xc00044ce70, 0xc000a21b00, 0x0, 0x0)
 
	/go/src/github.com/qri-io/qri/repo/store.go:47 +0x1f7
 
github.com/qri-io/qri/base.DatasetLogFromHistory(0x26ff040, 0xc0000480e0, 0x271faa0, 0xc00044ce70, 0xc000582800, 0x9, 0x0, 0x0, 0x2301664, 0x11, ...)
 
	/go/src/github.com/qri-io/qri/base/log.go:83 +0x135
 
github.com/qri-io/qri/base.constructDatasetLogFromHistory(0x26ff040, 0xc0000480e0, 0x271faa0, 0xc00044ce70, 0xc000582800, 0x9, 0xc0006fe150, 0x2e, 0x2301664, 0x11, ...)
 
	/go/src/github.com/qri-io/qri/base/log.go:140 +0x12c
 
github.com/qri-io/qri/base.DatasetLog.func1(0x271faa0, 0xc00044ce70, 0xc000582800, 0x9, 0xc000aa4090, 0x22, 0x2301664, 0x11, 0xc042536600, 0x34, ...)
 
	/go/src/github.com/qri-io/qri/base/log.go:69 +0x106
 
created by github.com/qri-io/qri/base.DatasetLog
 
	/go/src/github.com/qri-io/qri/base/log.go:68 +0x334
 
FAIL	github.com/qri-io/qri/cmd	19.462s
 
?   	github.com/qri-io/qri/cmd/generate	[no test files]
 ```
