### ISSUE TITLE
TestTwoActorRegistryIntegration is flaky, failed a few different ways on CI

### ISSUE THREAD

**Issue by dustmop** [qri-io/qri#1158]
```
    TestTwoActorRegistryIntegration: integration_test.go:40: 0 Peername:  nasim
          ProfileID: QmWYgD49r9HnuXEppQEq1a7SUUryja4QNs9E6XCH2PayCD
          Name:      world_bank_population
          Path:      /ipfs/QmVfExwDm79Eb8KcLxmtMyWESKiztqS8HXmezCLnVYcTMc
          FSIPath:   
          Published: true
        
    TestTwoActorRegistryIntegration: integration_test.go:288: json: cannot unmarshal number into Go value of type struct { Data []*dataset.Dataset; Meta struct { Error string; Status string; Code int } }
--- FAIL: TestTwoActorRegistryIntegration (0.13s)
```

also saw this:

```
=== RUN   TestTwoActorRegistryIntegration
    TestTwoActorRegistryIntegration: integration_test.go:160: registry qri path: /tmp/integration_two_actor_registry_registry515667419/qri
--- FAIL: TestTwoActorRegistryIntegration (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x198c82c]

goroutine 4265 [running]:
testing.tRunner.func1.1(0x1d68f60, 0x2e74fb0)
	/usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc00125a6c0)
	/usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0x1d68f60, 0x2e74fb0)
	/usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/qri-io/qri/remote.NewRemote(0x0, 0xc000453c40, 0x0, 0x0, 0x0, 0x1, 0x1, 0xc0006727e0)
	/go/src/github.com/qri-io/qri/remote/remote.go:133 +0x5dc
github.com/qri-io/qri/lib.(*NetworkIntegrationTestRunner).InitRegistry(0xc0011dded0, 0xc00125a6c0)
	/go/src/github.com/qri-io/qri/lib/integration_test.go:185 +0x4ee
github.com/qri-io/qri/lib.NewNetworkIntegrationTestRunner(...)
	/go/src/github.com/qri-io/qri/lib/integration_test.go:103
github.com/qri-io/qri/lib.TestTwoActorRegistryIntegration(0xc00125a6c0)
	/go/src/github.com/qri-io/qri/lib/integration_test.go:20 +0xdb
testing.tRunner(0xc00125a6c0, 0x2130b98)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357
FAIL	github.com/qri-io/qri/lib	1.053s
```

**Comment by dustmop** [comment]
Also saw this when running locally with `--count=10`:

```
--- FAIL: TestTwoActorRegistryIntegration (0.07s)
    integration_test.go:160: registry qri path: /var/folders/dr/99mxhb715495lk6rc4zy5dfr0000gn/T/integration_two_actor_registry_registry757214791/qri
panic: runtime error: index out of range [10] with length 10 [recovered]
	panic: runtime error: index out of range [10] with length 10

goroutine 1496 [running]:
testing.tRunner.func1.1(0x5393ca0, 0xc0041cb4a0)
	/usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc0006590e0)
	/usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0x5393ca0, 0xc0041cb4a0)
	/usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/qri-io/qri/config/test.GetTestPeerInfo(0xa, 0xc004a719e0)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/config/test/test_peers.go:48 +0x443
github.com/qri-io/qri/repo/test.(*testCryptoGenerator).GeneratePrivateKeyAndPeerID(0xc000040258, 0xc004a26480, 0x1ff, 0x0, 0x0)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/repo/test/generator.go:29 +0x2e
github.com/qri-io/qri/repo/test.newTempRepo(0x546eef1, 0x5, 0xc004a60720, 0x24, 0x5854060, 0xc000040258, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/repo/test/temp_repo.go:73 +0x284
github.com/qri-io/qri/repo/test.NewTempRepo(...)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/repo/test/temp_repo.go:43
github.com/qri-io/qri/lib.(*NetworkIntegrationTestRunner).InitNasim(0xc00017fed0, 0xc0006590e0, 0x404af01)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/lib/integration_test.go:120 +0x13f
github.com/qri-io/qri/lib.TestTwoActorRegistryIntegration(0xc0006590e0)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/lib/integration_test.go:23 +0x115
testing.tRunner(0xc0006590e0, 0x561cf40)
	/usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1043 +0x357
FAIL	github.com/qri-io/qri/lib	4.221s
FAIL
```

**Comment by dustmop** [comment]
this trace:
```
panic: runtime error: index out of range [10] with length 10 [recovered]
	panic: runtime error: index out of range [10] with length 10

goroutine 1496 [running]:
testing.tRunner.func1.1(0x5393ca0, 0xc0041cb4a0)
	/usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc0006590e0)
	/usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0x5393ca0, 0xc0041cb4a0)
	/usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/qri-io/qri/config/test.GetTestPeerInfo(0xa, 0xc004a719e0)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/config/test/test_peers.go:48 +0x443
```

Is caused because the defaultCryptoGenerator is running out of test peers to hand out. I suppose this global default may be shared across test runs?

Some possible solutions:
* Add more test peers, though this is really just band-aiding over the problem
* Construct a CryptoGenerator at the test start and pass it down explicitly
* Scope the  peers that get handed out automatically based on the test name or something. This probably won't work when run with --count=1

**Comment by dustmop** [comment]
A new failure:

```
=== RUN   TestTwoActorRegistryIntegration
    TestTwoActorRegistryIntegration: integration_test.go:163: registry qri path: /tmp/integration_two_actor_registry_registry188583076/qri
22:22:54.316 CRITI        lib: publishing dataset: remote response: 404 404 page not found
 integration_test.go:282
FAIL	github.com/qri-io/qri/lib	1.375s
```

**Comment by dustmop** [comment]
Saw this, which looks like it may get fixed by https://github.com/qri-io/dag/pull/28.

```
    TestTwoActorRegistryIntegration: integration_test.go:53: nasim/world_bank_population@/ipfs/QmPRGynriBe8JMZTQY2KcY6bNr4bW7aWxQajUi5wPKh1jX
🗼 fetched from registry
2/7 blocks transferred
3/7 blocks transferred
4/7 blocks transferred
5/7 blocks transferred
2020/03/17 13:23:58 http: panic serving 127.0.0.1:61644: runtime error: index out of range [3] with length 0
goroutine 7814 [running]:
net/http.(*conn).serve.func1(0xc00e37bd60)
	/usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x5393ac0, 0xc009fb6920)
	/usr/local/go/src/runtime/panic.go:973 +0x396
github.com/google/flatbuffers/go.GetInt32(...)
	/Users/dlong/go/pkg/mod/github.com/google/flatbuffers@v1.11.0/go/encode.go:85
github.com/google/flatbuffers/go.GetUOffsetT(...)
	/Users/dlong/go/pkg/mod/github.com/google/flatbuffers@v1.11.0/go/encode.go:121
github.com/qri-io/qri/repo/repo_fbs.GetRootAsReflist(...)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/repo/repo_fbs/Reflist.go:14
github.com/qri-io/qri/repo.UnmarshalRefsFlatbuffer(0xc0067dea00, 0x0, 0x200, 0x0, 0x200, 0x0, 0x0, 0x406bf10)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/repo/serialize.go:48 +0x2e6
github.com/qri-io/qri/repo/fs.(*Refstore).refs(0xc0069a6d60, 0x40408dc, 0xc009e3c480, 0x300000002, 0xc009e3c480, 0xc0069a6be0)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/repo/fs/refstore.go:133 +0x2fd
github.com/qri-io/qri/repo/fs.Refstore.GetRef(0xc004e8f3b0, 0x65, 0x8, 0x5867c00, 0xc000798bc0, 0xc000b733b5, 0x5, 0xc00694d950, 0x22, 0xc000b73358, ...)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/repo/fs/refstore.go:62 +0x65
github.com/qri-io/qri/repo.CanonicalizeDatasetRef(0x58793a0, 0xc009f80a10, 0xc0069a7578, 0x22, 0xc000b733b5)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/repo/store.go:47 +0x1f7
github.com/qri-io/qri/remote.(*Remote).dsPushComplete(0xc000b357a0, 0x585bd20, 0xc003321080, 0xc006ef60c0, 0x0, 0xc00309ae10, 0x7, 0x9, 0xc006ef61e0, 0xc000a02758, ...)
	/Users/dlong/dev/code/go/qri/src/github.com/qri-io/qri/remote/remote.go:323 +0xd1
github.com/qri-io/dag/dsync.(*Dsync).finalizeReceive(0xc006f81a40, 0xc0009ac100, 0x0, 0x0)
	/Users/dlong/go/pkg/mod/github.com/qri-io/dag@v0.2.1-0.20191025201336-254aa177fbd7/dsync/dsync.go:441 +0x46e
github.com/qri-io/dag/dsync.(*Dsync).ReceiveBlock(0xc006f81a40, 0xc003224976, 0xa, 0xc003224986, 0x2e, 0xc005d14e00, 0x2f, 0x200, 0x0, 0x0, ...)
	/Users/dlong/go/pkg/mod/github.com/qri-io/dag@v0.2.1-0.20191025201336-254aa177fbd7/dsync/dsync.go:398 +0x26a
github.com/qri-io/dag/dsync.HTTPRemoteHandler.func1(0x5854fe0, 0xc002e6dce0, 0xc00019d800)
	/Users/dlong/go/pkg/mod/github.com/qri-io/dag@v0.2.1-0.20191025201336-254aa177fbd7/dsync/http.go:255 +0xa6b
net/http.HandlerFunc.ServeHTTP(0xc00623fec0, 0x5854fe0, 0xc002e6dce0, 0xc00019d800)
	/usr/local/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0017b4c80, 0x5854fe0, 0xc002e6dce0, 0xc00019d800)
	/usr/local/go/src/net/http/server.go:2387 +0x1a5
net/http.serverHandler.ServeHTTP(0xc00032f340, 0x5854fe0, 0xc002e6dce0, 0xc00019d800)
	/usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc00e37bd60, 0x585bca0, 0xc005dd31c0)
	/usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x35c
13:23:58.921 CRITI        lib: publishing dataset: Put "http://127.0.0.1:61623/remote/dsync?sid=jPhSGNkzLa&hash=QmZgHh3LHZLgx8fHejXteYaQhkd9Yx31MyKyGYCga9h3Bk": EOF integration_test.go:282
6/7 blocks transferred
FAIL	github.com/qri-io/qri/lib	20.264s
FAIL
```

**Comment by dustmop** [comment]
Saw this again:
```
=== RUN   TestTwoActorRegistryIntegration
    TestTwoActorRegistryIntegration: integration_test.go:163: registry qri path: /tmp/integration_two_actor_registry_registry055142879/qri
03:11:42.970 CRITI        lib: publishing dataset: remote response: 404 404 page not found
 integration_test.go:282
FAIL	github.com/qri-io/qri/lib	1.148s
```

**Comment by dustmop** [comment]
This used to be a segfault, is now being caught, due to https://github.com/qri-io/qri/pull/1211. But need to look into why this is happening at all:

```
=== RUN   TestTwoActorRegistryIntegration
    TestTwoActorRegistryIntegration: integration_test.go:163: registry qri path: /tmp/integration_two_actor_registry_registry444237245/qri
    TestTwoActorRegistryIntegration: integration_test.go:190: remote requires a non-nil node
--- FAIL: TestTwoActorRegistryIntegration (0.01s)
```
