### ISSUE TITLE
Calling ds.get_body() on a transform where the dataset has no history causes a crash

### ISSUE THREAD

**Issue by chriswhong** [qri-io/qri#1651]
This is coming up in the workflow editor in qrimatic.  For my use case I am working on a brand new dataset and would like to check if there is an existing body so will know whether to add a header row before calling ds.set_body()

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x50e9bd4]

goroutine 23742 [running]:
github.com/qri-io/dataset.(*Dataset).BodyFile(...)
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/dataset@v0.2.1-0.20210128201320-3b1209495e96/dataset.go:336
github.com/qri-io/qri/transform/startf/ds.(*Dataset).GetBody(0xc0018fc960, 0xc00116b9f0, 0xc0018fcae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5cd0bc0, ...)
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/qri@v0.9.14-0.20210217202507-0fa42078cdd7/transform/startf/ds/dataset.go:235 +0x174
go.starlark.net/starlark.(*Builtin).CallInternal(0xc0018fcae0, 0xc00116b9f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x401802e, 0x8f41ba8, ...)
	/Users/chriswhong/go/pkg/mod/go.starlark.net@v0.0.0-20200619143648-50ca820fafb9/starlark/value.go:654 +0x8b
go.starlark.net/starlark.Call(0xc00116b9f0, 0x5cd0200, 0xc0018fcae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5cd0bc0, ...)
	/Users/chriswhong/go/pkg/mod/go.starlark.net@v0.0.0-20200619143648-50ca820fafb9/starlark/eval.go:1085 +0x190
go.starlark.net/starlark.(*Function).CallInternal(0xc001a953c0, 0xc00116b9f0, 0xc001de0360, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc00102d800, 0x8a40108, ...)
	/Users/chriswhong/go/pkg/mod/go.starlark.net@v0.0.0-20200619143648-50ca820fafb9/starlark/interp.go:314 +0x3fff
go.starlark.net/starlark.Call(0xc00116b9f0, 0x5cd0280, 0xc001a953c0, 0xc001de0360, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/chriswhong/go/pkg/mod/go.starlark.net@v0.0.0-20200619143648-50ca820fafb9/starlark/eval.go:1085 +0x190
github.com/qri-io/qri/transform/startf.(*StepRunner).callTransformFunc(0xc0016f1d40, 0x5cc8b80, 0xc000083bc0, 0xc00116b9f0, 0xc001a953c0, 0xc00145c4b0, 0xc0014b7af8, 0xc0018fc930)
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/qri@v0.9.14-0.20210217202507-0fa42078cdd7/transform/startf/exec_step.go:158 +0x17a
github.com/qri-io/qri/transform/startf.(*StepRunner).callStepFunc(0xc0016f1d40, 0x5cc8b80, 0xc000083bc0, 0xc00116b9f0, 0xc0014c7b00, 0x9, 0xc00145c4b0, 0x0, 0x0)
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/qri@v0.9.14-0.20210217202507-0fa42078cdd7/transform/startf/exec_step.go:122 +0x1dd
github.com/qri-io/qri/transform/startf.(*StepRunner).RunStep(0xc0016f1d40, 0x5cc8b80, 0xc000083bc0, 0xc00145c4b0, 0xc00116b900, 0x0, 0x0)
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/qri@v0.9.14-0.20210217202507-0fa42078cdd7/transform/startf/exec_step.go:101 +0x48e
github.com/qri-io/qri/transform.(*Service).Apply.func1(0xc000775300, 0xc000317ce0, 0xc001b44890, 0xc000775380, 0xc000775320, 0x8f38ec0, 0xc000116fa0, 0xc000f41230, 0x24, 0xc00145c4b0, ...)
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/qri@v0.9.14-0.20210217202507-0fa42078cdd7/transform/apply.go:206 +0xa7c
created by github.com/qri-io/qri/transform.(*Service).Apply
	/Users/chriswhong/go/pkg/mod/github.com/qri-io/qri@v0.9.14-0.20210217202507-0fa42078cdd7/transform/apply.go:120 +0x410
(base) [chriswhong@mbp ~/qri/qrimatic/qrimatic (master *)]$ 
```

**Comment by dustmop** [comment]
Fixed by https://github.com/qri-io/dataset/commit/84c88ebf19af9365df503f358436c3ce2686b3d9, will be fixed in core once we update the dependency.
